### ISSUE TITLE
TensorFlow workflow

### ISSUE THREAD

**Issue by morganekmefjord** [pharmbio/kubeflow-pipelines#2]
# Description
Tensor Flow Example utilizing the Kensert CNN example in a pipeline in the following steps:
1. Ingestion
2. Training
3. Model checkpointing
4. Build image for deployment
5. Send image to serving

# Tasks
- [ ] Implement steps 1-5 in kubeflow pipeline
- [ ] Connect pipeline to serving component (OpenFaas?)
- [ ] Automate entire process, set up some form of trigger?

# Acceptance Criterias
Automated pipeline from step 1 to step 5.
